name: Fx.TextContinu
author: Nicolas de Marqué
category: Effect, Text Transformation
tags: [effects, morph, text]
current: 1.0
docs: http://github.com/nicodmf/TextContinu/blob/master/mootools/README.md
demo: http://nicodmf.github.com/TextContinu/demos/mootools.html